name: Laborum Alert Bot
on:
  schedule:
    - cron: '0 13 * * *' # Corre a las 8:00 AM hora de Perú (13:00 UTC)
  workflow_dispatch: # Botón para probarlo a mano

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run Script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python script.py
