name: Buscador Diario de Empleos

on:
  schedule:
    - cron: '0 9 * * *' # Esto corre todos los días a las 9:00 AM UTC
  workflow_dispatch: # Esto permite que tú lo actives manualmente para probar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v2
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Instalar herramientas
        run: pip install requests beautifulsoup4
      - name: Ejecutar Scraper
        env:
          TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python script.py
